# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TECTALIC TECHBLOG
email: info@tectalic.de
description: > # this means to ignore newlines until "baseurl:"
  All about modern web technologies like React.js, Redux, Ruby on Rails, Meteor and so on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tectalic.github.io" # the base hostname & protocol for your site
twitter_username: tectalic
github_username:  tectalic
google_analytics: UA-74316640-2

# Build settings
markdown: kramdown
highlighter: rouge

# exclude vendor folder to avoid error => https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
